### ISSUE TITLE
error when executing syncer

### ISSUE THREAD

**Issue by emad-elsaid** [R4md4c/youtube-channel-downloader#1]
my config file is as follows : 

``` yaml
API_KEY: "********************************"

channels:
    - UCp0aBUts6iAokAR3_02QwSw

users:
    - mazzika
```

after executing the channel-syncer.py i get this error

``` bash
➜  youtube-channel-syncer git:(master) ✗ python channel-syncer.py
Traceback (most recent call last):
  File "channel-syncer.py", line 27, in <module>
    channel_item_array = api.list_channel_content(channel)
  File "/home/eelsaid/Desktop/youtube-channel-syncer/YoutubeAPI.py", line 22, in list_channel_content
    response = request.execute()
  File "/usr/lib/python2.6/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/apiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/youtube/v3/search?part=snippet%2C+id&key=*****************************%E2%80%AC%E2%80%8E&alt=json&channelId=UCp0aBUts6iAokAR3_02QwSw&order=date&maxResults=50 returned "Bad Request">

```

my system info is as follows :

``` bash
Linux EElSaid-PC 2.6.32-431.20.3.el6.centos.plus.x86_64 #1 SMP Thu Jun 19 23:04:15 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by emad-elsaid** [comment]
i had a non-printable characters at teh end of API key, that was my problem when i cleared them everything works fine.
